# Testing and verifying the outputs of various operations

In [2]:
import numpy as np

In [ ]:
arr = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
], type)

In [5]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr.shape # its 4 x 4

(4, 4)

In [6]:
arr @ arr

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [9]:
arr2 = arr.reshape(-1, 1) # flattened it into a column vector. `-1` is a "whatever works" argument, 1 is what we want the shape to support

In [11]:
arr2.shape # So we asked (*, 1) to be the final shape above basically, and it got resized to match this

(16, 1)

In [12]:
arr3 = arr.reshape(1, -1) # this is asking the data to be reshaped into a shape that matches (1, *)

In [13]:
arr3.shape # So we asked for (1, *) and it got resized to match this (row vector)

(1, 16)

In [14]:
arr4 = arr3.reshape(4, 4) # we are asking to recover the 4 x 4 original shape.

In [ ]:
arr4.shape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
print(arr)
print()
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
arr5 = arr4.reshape(4, 4, 1) # the splits must actually make sense, I guess. The flat 1D list of numbers (left to right) must be splittable into equal size arrays

In [ ]:
arr5 # so this is a nested one. Same idea as arr/arr4 but every element is now a vector of size 1 in the middle

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]]])

In [21]:
arr5.size

16

In [22]:
arr6 = arr5.reshape(-1)
# arr6 = arr5.reshape(16) # aka arr5.size
# arr6 = arr5.flatten()
# arr6 = arr5.ravel()

In [24]:
arr6 # flat 1D vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [25]:
arr6.shape

(16,)

In [ ]:
arr6.reshape(6, -1) # won't work because it can't be split up nicely

ValueError: cannot reshape array of size 16 into shape (6,newaxis)

In [29]:
import numpy as np
from IPython.display import Math, display

def latex_matrix(A, fmt="{:.3g}"):
    rows = [
        " & ".join(fmt.format(x) for x in row)
        for row in A
    ]
    body = r" \\ ".join(rows)
    return r"\begin{bmatrix}" + body + r"\end{bmatrix}"

A = np.random.randn(3, 4)
display(Math(latex_matrix(A)))


<IPython.core.display.Math object>

In [2]:
import torch

a = []

for i in range(10):
    a.append(torch.tensor(i + 0.))

In [3]:
a

[tensor(0.),
 tensor(1.),
 tensor(2.),
 tensor(3.),
 tensor(4.),
 tensor(5.),
 tensor(6.),
 tensor(7.),
 tensor(8.),
 tensor(9.)]

In [4]:
torch.stack(a)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
torch.tensor(a)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
tensor1 = torch.tensor([
    [1., 2., 3., 4.],
    [1., 2., 3., 4.],
    [1., 2., 3., 4.],
])
tensor2 = torch.tensor([
    [5., 6.],
    [5., 6.],
    [5., 6.],
])

concatted = torch.concat([tensor1, tensor2], dim=1)

concatted
# Extends the elements in tensor1 by appending the ones of tensor2 to them

tensor([[1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.]])

Getting them back out...

In [5]:
concatted[:, :4]

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [7]:
concatted[:, 4:]

tensor([[5., 6.],
        [5., 6.],
        [5., 6.]])

In [11]:
concatted.dtype

torch.float32